
services:
  maskrcnn:
    image: maskrcnn_test
    build: 
      context: ../
      dockerfile: Dockerfile_Local/Dockerfile
    ports:
      - "8888:8888"  # effettua il binding della porta 8888 tra quella dell'host e quella del container
      - "12000:12000" # per codeStream
      - "12002:12002" # per codeStream
    volumes:
      # passo la cartella del codice come volume
      - ./../Mask_RCNN:/root/Mask_RCNN/
      - ./../datasets/ISIC2018/dataset:/root/isic2018
      - /tmp/.X11-unix:/tmp/.X11-unix    # necessario per l'X11 forwarding
      - ~/.Xauthority:/root/.Xauthority  # necessario per l'X11 forwarding
      - ./../.git:/root/.git # to have git lens and codeStream, never commit from inside the container
      - ./../.gitignore:/root/.gitignore
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    runtime: nvidia  # abilita l'utilizzo delle gpu del sistema
    environment:
      DISPLAY: $DISPLAY  # necessario per l'X11 forwarding
        