
services:
    ds_rgb_mean:
      image: jjanzic/docker-python3-opencv
      ports:
        - "8888:8888"  # effettua il binding della porta 8888 tra quella dell'host e quella del container
        - "12000:12000" # per codeStream
        - "12002:12002" # per codeStream
      volumes:
        # passo la cartella del codice come volume
        - ./../:/root
        - /tmp/.X11-unix:/tmp/.X11-unix    # necessario per l'X11 forwarding
        - ~/.Xauthority:/root/.Xauthority  # necessario per l'X11 forwarding
      stdin_open: true # docker run -i
      tty: true        # docker run -t
      runtime: nvidia  # abilita l'utilizzo delle gpu del sistema
      environment:
        DISPLAY: $DISPLAY  # necessario per l'X11 forwarding
          